"""Mock Collaboration Adapter for deterministic closed-loop simulation."""

from collections.abc import Callable

from orgpilot.adapter.base import CollaborationAdapter
from orgpilot.adapter.contracts import DeadlineUpdate, PayloadContractError
from orgpilot.domain.enums import CommandStatus
from orgpilot.domain.models import ActionCommand, ActionResult
from orgpilot.events.models import (
    EventSource,
    OrgEvent,
    TaskUpdatedEvent,
    TaskUpdatedPayload,
)


class MockCollaborationAdapter(CollaborationAdapter):
    """Deterministic in-memory adapter that records commands and simulates responses."""

    def __init__(self, project_id: str = "test-project") -> None:
        self.project_id = project_id
        self.audit_log: list[tuple[ActionCommand, ActionResult]] = []
        self._generated_events: list[OrgEvent] = []
        self._scripted_replies: dict[str, list[OrgEvent]] = {}
        self._custom_responders: list[
            Callable[[ActionCommand], OrgEvent | list[OrgEvent] | None]
        ] = []

    def script_reply(self, key: str, event: OrgEvent) -> None:
        """Scripts an event to be emitted when a matching command (by action_id or target) runs."""
        self._scripted_replies.setdefault(key, []).append(event)

    def add_responder(
        self, responder: Callable[[ActionCommand], OrgEvent | list[OrgEvent] | None]
    ) -> None:
        """Registers a dynamic response function."""
        self._custom_responders.append(responder)

    def pop_generated_events(self) -> list[OrgEvent]:
        """Retrieves and clears events generated by simulated replies or executions."""
        events = list(self._generated_events)
        self._generated_events.clear()
        return events

    def send_private_message(self, command: ActionCommand) -> ActionResult:
        result = ActionResult(
            command_id=command.command_id,
            action_id=command.action_id,
            status=CommandStatus.SUCCESS,
            output={"sent_to": command.targets, "payload": command.payload},
            executed_at=command.created_at,
        )
        self.audit_log.append((command, result))
        self._trigger_replies(command)
        return result

    def request_approval(self, command: ActionCommand, approver_id: str) -> ActionResult:
        result = ActionResult(
            command_id=command.command_id,
            action_id=command.action_id,
            status=CommandStatus.SUCCESS,
            output={
                "status": "approval_requested",
                "approver_id": approver_id,
                "payload": command.payload,
            },
            executed_at=command.created_at,
        )
        self.audit_log.append((command, result))
        self._trigger_replies(command)
        return result

    def update_task(self, command: ActionCommand) -> ActionResult:
        if command.approved_by is None:
            result = ActionResult(
                command_id=command.command_id,
                action_id=command.action_id,
                status=CommandStatus.REJECTED,
                error="task modification rejected: missing approval",
                executed_at=command.created_at,
            )
            self.audit_log.append((command, result))
            return result

        try:
            update = DeadlineUpdate.from_payload(command.payload)
        except PayloadContractError as exc:
            result = ActionResult(
                command_id=command.command_id,
                action_id=command.action_id,
                status=CommandStatus.FAILED,
                error=str(exc),
                executed_at=command.created_at,
            )
            self.audit_log.append((command, result))
            return result

        event = TaskUpdatedEvent(
            project_id=self.project_id,
            event_id=f"evt-mock-update-{command.command_id}",
            event_type="task.updated",
            source=EventSource.TASK,
            source_ref=f"adapter:command:{command.command_id}",
            actor_id=command.approved_by,
            occurred_at=command.created_at,
            received_at=command.created_at,
            payload=TaskUpdatedPayload(
                task_id=update.task_id,
                deadline=update.new_deadline,
            ),
        )
        self._generated_events.append(event)

        result = ActionResult(
            command_id=command.command_id,
            action_id=command.action_id,
            status=CommandStatus.SUCCESS,
            output={"task_id": update.task_id, "updated_fields": command.payload},
            executed_at=command.created_at,
        )
        self.audit_log.append((command, result))
        return result

    def notify_group(self, command: ActionCommand) -> ActionResult:
        result = ActionResult(
            command_id=command.command_id,
            action_id=command.action_id,
            status=CommandStatus.SUCCESS,
            output={"targets": command.targets, "payload": command.payload},
            executed_at=command.created_at,
        )
        self.audit_log.append((command, result))
        return result

    def _trigger_replies(self, command: ActionCommand) -> None:
        # Check scripted replies by action_id, command_id, or targets
        keys_to_check = [command.action_id, command.command_id, *command.targets]
        for key in keys_to_check:
            if key in self._scripted_replies and self._scripted_replies[key]:
                replies = self._scripted_replies[key]
                self._generated_events.extend(replies)
                self._scripted_replies[key] = []

        # Check dynamic custom responders
        for responder in self._custom_responders:
            resp = responder(command)
            if resp is not None:
                if isinstance(resp, list):
                    self._generated_events.extend(resp)
                else:
                    self._generated_events.append(resp)
